using System.Security.Cryptography;
using Carter;
using Fei.Is.Api.Common.Errors;
using Fei.Is.Api.Data.Contexts;
using Fei.Is.Api.Data.Models;
using Fei.Is.Api.Extensions;
using FluentResults;
using FluentValidation;
using MediatR;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.EntityFrameworkCore;

namespace Fei.Is.Api.Features.System.Commands;

public static class CreateEdgeNode
{
    public record Request(string Name, string? Token);

    public sealed class Endpoint : ICarterModule
    {
        public void AddRoutes(IEndpointRouteBuilder app)
        {
            app.MapPost(
                    "system/edge-nodes",
                    async Task<Results<Created<Response>, ValidationProblem>> (
                        IMediator mediator,
                        Request request,
                        CancellationToken cancellationToken
                    ) =>
                    {
                        var result = await mediator.Send(new Command(request), cancellationToken);

                        if (result.HasError<ValidationError>())
                        {
                            return TypedResults.ValidationProblem(result.ToValidationErrors());
                        }

                        return TypedResults.Created($"system/edge-nodes/{result.Value.Id}", result.Value);
                    }
                )
                .RequireAuthorization("Admin")
                .WithName(nameof(CreateEdgeNode))
                .WithTags("System")
                .WithOpenApi(o =>
                {
                    o.Summary = "Create edge node setting";
                    o.Description = "Adds a new edge node with an optional token. When token is not provided, it is autogenerated.";
                    return o;
                });
        }
    }

    public record Command(Request Request) : IRequest<Result<Response>>;

    public sealed class Handler(AppDbContext context, IValidator<Command> validator) : IRequestHandler<Command, Result<Response>>
    {
        public async Task<Result<Response>> Handle(Command message, CancellationToken cancellationToken)
        {
            var validationResult = validator.Validate(message);
            if (!validationResult.IsValid)
            {
                return Result.Fail(new ValidationError(validationResult));
            }

            var requestedToken = message.Request.Token?.Trim();

            string token;
            if (string.IsNullOrWhiteSpace(requestedToken))
            {
                token = await GenerateUniqueTokenAsync(context, cancellationToken);
            }
            else
            {
                var tokenExists = await context.EdgeNodes.AnyAsync(edgeNode => edgeNode.Token == requestedToken, cancellationToken);
                if (tokenExists)
                {
                    return Result.Fail(new ValidationError(nameof(Request.Token), "Token is already in use"));
                }

                token = requestedToken;
            }

            var edgeNode = new EdgeNode
            {
                Name = message.Request.Name.Trim(),
                Token = token
            };

            await context.EdgeNodes.AddAsync(edgeNode, cancellationToken);
            await context.SaveChangesAsync(cancellationToken);

            return Result.Ok(
                new Response(
                    edgeNode.Id,
                    edgeNode.Name,
                    edgeNode.Token,
                    edgeNode.CreatedAt,
                    edgeNode.UpdatedAt
                )
            );
        }

        private static async Task<string> GenerateUniqueTokenAsync(AppDbContext context, CancellationToken cancellationToken)
        {
            while (true)
            {
                var token = Convert.ToHexString(RandomNumberGenerator.GetBytes(32)).ToLowerInvariant();
                var exists = await context.EdgeNodes.AnyAsync(edgeNode => edgeNode.Token == token, cancellationToken);

                if (!exists)
                {
                    return token;
                }
            }
        }
    }

    public record Response(Guid Id, string Name, string Token, DateTime CreatedAt, DateTime UpdatedAt);

    public sealed class Validator : AbstractValidator<Command>
    {
        public Validator()
        {
            RuleFor(command => command.Request.Name).NotEmpty().MaximumLength(128);
            RuleFor(command => command.Request.Token)
                .MaximumLength(256)
                .When(command => !string.IsNullOrWhiteSpace(command.Request.Token));
        }
    }
}
