// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace DataPointFlatBuffers
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct DataPointFbs : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static DataPointFbs GetRootAsDataPointFbs(ByteBuffer _bb) { return GetRootAsDataPointFbs(_bb, new DataPointFbs()); }
  public static DataPointFbs GetRootAsDataPointFbs(ByteBuffer _bb, DataPointFbs obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DataPointFbs __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Tag { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTagBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetTagBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetTagArray() { return __p.__vector_as_array<byte>(4); }
  public double Value { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : (double)0.0; } }
  public long Ts { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }
  public double Latitude { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : (double)0.0; } }
  public double Longitude { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : (double)0.0; } }
  public int GridX { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int GridY { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<DataPointFlatBuffers.DataPointFbs> CreateDataPointFbs(FlatBufferBuilder builder,
      StringOffset tagOffset = default(StringOffset),
      double value = 0.0,
      long ts = 0,
      double latitude = 0.0,
      double longitude = 0.0,
      int grid_x = 0,
      int grid_y = 0) {
    builder.StartTable(7);
    DataPointFbs.AddLongitude(builder, longitude);
    DataPointFbs.AddLatitude(builder, latitude);
    DataPointFbs.AddTs(builder, ts);
    DataPointFbs.AddValue(builder, value);
    DataPointFbs.AddGridY(builder, grid_y);
    DataPointFbs.AddGridX(builder, grid_x);
    DataPointFbs.AddTag(builder, tagOffset);
    return DataPointFbs.EndDataPointFbs(builder);
  }

  public static void StartDataPointFbs(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddTag(FlatBufferBuilder builder, StringOffset tagOffset) { builder.AddOffset(0, tagOffset.Value, 0); }
  public static void AddValue(FlatBufferBuilder builder, double value) { builder.AddDouble(1, value, 0.0); }
  public static void AddTs(FlatBufferBuilder builder, long ts) { builder.AddLong(2, ts, 0); }
  public static void AddLatitude(FlatBufferBuilder builder, double latitude) { builder.AddDouble(3, latitude, 0.0); }
  public static void AddLongitude(FlatBufferBuilder builder, double longitude) { builder.AddDouble(4, longitude, 0.0); }
  public static void AddGridX(FlatBufferBuilder builder, int gridX) { builder.AddInt(5, gridX, 0); }
  public static void AddGridY(FlatBufferBuilder builder, int gridY) { builder.AddInt(6, gridY, 0); }
  public static Offset<DataPointFlatBuffers.DataPointFbs> EndDataPointFbs(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<DataPointFlatBuffers.DataPointFbs>(o);
  }
}


static public class DataPointFbsVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Tag*/, false)
      && verifier.VerifyField(tablePos, 6 /*Value*/, 8 /*double*/, 8, false)
      && verifier.VerifyField(tablePos, 8 /*Ts*/, 8 /*long*/, 8, false)
      && verifier.VerifyField(tablePos, 10 /*Latitude*/, 8 /*double*/, 8, false)
      && verifier.VerifyField(tablePos, 12 /*Longitude*/, 8 /*double*/, 8, false)
      && verifier.VerifyField(tablePos, 14 /*GridX*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 16 /*GridY*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
