export enum JobStatusEnum {
  JOB_QUEUED = 'JOB_QUEUED',
  JOB_IN_PROGRESS = 'JOB_IN_PROGRESS',
  JOB_PAUSED = 'JOB_PAUSED',
  JOB_SUCCEEDED = 'JOB_SUCCEEDED',
  JOB_REJECTED = 'JOB_REJECTED',
  JOB_FAILED = 'JOB_FAILED',
  JOB_TIMED_OUT = 'JOB_TIMED_OUT',
  JOB_CANCELED = 'JOB_CANCELED',
}
