// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace JobFlatBuffers
{

public enum JobControlEnumFbs : sbyte
{
  JOB_PAUSE = 0,
  JOB_RESUME = 1,
  JOB_SKIP_STEP = 2,
  JOB_SKIP_CYCLE = 3,
  JOB_CANCEL = 4,
};


}
