// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace JobFlatBuffers
{

public enum JobStatusFbsEnum : sbyte
{
  JOB_QUEUED = 0,
  JOB_IN_PROGRESS = 1,
  JOB_PAUSED = 2,
  JOB_SUCCEEDED = 3,
  JOB_REJECTED = 4,
  JOB_FAILED = 5,
  JOB_TIMED_OUT = 6,
  JOB_CANCELED = 7,
};


}
