apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: marvixs/iot-is-backend
        imagePullPolicy: Never
        # envFrom:
        # - configMapRef:
        #     name: backend-config
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        - name: POSTGRES_PASSWORD
          value: "password"
        - name: TIMESCALE_PASSWORD
          value: "password"
        - name: EMQX__HOST
          value: "emqx"
        - name: EMQX__USERNAME
          value: "backend"
        - name: EMQX__PASSWORD
          value: "YdA#zY+ti2V£N46Q0si0Id"
        - name: JWT__SECRET
          value: "vnstmpXjmJVMCeIqvwGDOldvaRNQB7DE"
        - name: JWT__ISSUER
          value: "localhost"
        - name: JWT__AUDIENCE
          value: "localhost"
        - name: CORS__ALLOWED_ORIGINS
          value: "http://localhost:9000"
        ports:
        - containerPort: 8080
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 8080
  type: LoadBalancer