---
apiVersion: v1
kind: Service
metadata:
  name: emqx-service
spec:
  type: LoadBalancer  # Expose EMQX externally
  ports:
    - port: 1883      # MQTT
      targetPort: 1883
    - port: 8883      # MQTT over SSL/TLS
      targetPort: 8883
    - port: 18083     # EMQX Dashboard
      targetPort: 18083
  selector:
    app: emqx