apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg
spec:
  serviceName: "pg"
  replicas: 1
  selector:
    matchLabels:
      app: pg
  template:
    metadata:
      labels:
        app: pg
    spec:
      containers:
        - name: pg
          image: postgres:16-alpine3.20
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: env-config
          env:
            - name: POSTGRES_USER
              value: "is"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "is_sdg"
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: pg
spec:
  type: LoadBalancer
  ports:
    - port: 5432
  selector:
    app: pg
