apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timescaledb
spec:
  serviceName: "timescaledb"
  replicas: 1
  selector:
    matchLabels:
      app: timescaledb
  template:
    metadata:
      labels:
        app: timescaledb
    spec:
      containers:
        - name: timescaledb
          image: timescale/timescaledb-ha:pg16.4-ts2.16.1
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: env-config
          env:
            - name: POSTGRES_USER
              value: "is"
            - name: POSTGRES_PASSWORD
              value: "password"
            - name: POSTGRES_DB
              value: "is_sdg"
          volumeMounts:
            - name: timescaledb-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: timescaledb-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: timescaledb
spec:
  type: LoadBalancer  # Headless service for StatefulSet
  ports:
    - port: 5433
      targetPort: 5432
  selector:
    app: timescaledb
